name: 'Run tests'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  # Any checks that run pre-build
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      -
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.19'
      #-
      #  name: Start test infrastructure
      #  shell: bash
      #  run: |
      #    make setup
      -
        name: Run tests
        shell: bash
        run: |
          # make test
          TEST_ZONE_NAME=example.com. make test
          
